{% set name = "slotscheck" %}
{% set version = "0.16.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/slotscheck-{{ version }}.tar.gz
  sha256: 6cae3e73808121cf63c1bc638c3b5ae7e10f651323ad3cf38790ce005b77e221

build:
  noarch: python
  number: 1
  entry_points:
    - slotscheck = slotscheck.cli:root
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - poetry-core >=1.0.0
    - pip
    - python >=3.7,<4
  run:
    - click >=8.0,<9.0
    - importlib-metadata >=1,<6
    - python >=3.7,<4
    - tomli >=0.2.6,<3.0.0
    - typing-extensions >=4.1,<5

test:
  imports:
    - slotscheck
  commands:
    - pip check
    - slotscheck --help
  requires:
    - pip

about:
  home: https://github.com/ariebovenberg/slotscheck
  doc_url: https://slotscheck.readthedocs.io/en/latest/
  summary: Validate your __slots__
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
