{% set name = "slotscheck" %}
{% set version = "0.14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/slotscheck-{{ version }}.tar.gz
  sha256: 710b14fa002bda4a4e68777b067381f7299242c6a6965f361b96f2509b76db91

build:
  noarch: python
  number: 0
  entry_points:
    - slotscheck = slotscheck.cli:root
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - poetry-core >=1.0.0
    - pip
    - python >=3.7
  run:
    - click >=8.0,<9.0
    - importlib-metadata >=1,<5
    - python >=3.7
    - tomli >=0.2.6,<3.0.0

test:
  imports:
    - slotscheck
  commands:
    - pip check
    - slotscheck --help
  requires:
    - pip

about:
  home: https://github.com/ariebovenberg/slotscheck
  doc_url: https://slotscheck.readthedocs.io/en/latest/
  summary: Validate your __slots__
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
