{% set name = "slotscheck" %}
{% set version = "0.17.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/slotscheck-{{ version }}.tar.gz
  sha256: 4f89d7b3668b645ba0518e497556ebf16eb3d5185092bf22b910959c740191b3

build:
  noarch: python
  number: 0
  entry_points:
    - slotscheck = slotscheck.cli:root
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - poetry-core >=1.0.0
    - pip
    - python >=3.8,<4.0
  run:
    - click >=8.0.0,<9.0.0
    - python >=3.8,<4.0
    - tomli >=0.2.6,<3.0.0

test:
  imports:
    - slotscheck
  commands:
    - pip check
    - slotscheck --help
  requires:
    - pip

about:
  home: https://github.com/ariebovenberg/slotscheck
  doc_url: https://slotscheck.readthedocs.io/en/latest/
  summary: Validate your __slots__
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
