{% set name = "slotscheck" %}
{% set version = "0.19.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/slotscheck-{{ version }}.tar.gz
  sha256: 6146b7747f8db335a00a66b782f86011b74b995f61746dc5b36a9e77d5326013

build:
  noarch: python
  number: 1
  entry_points:
    - slotscheck = slotscheck.cli:root
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - poetry-core >=1.9.0
    - pip
    - python {{ python_min }}
  run:
    - click >=8.0.0,<9.0.0
    - python >={{ python_min }},<4.0
    - tomli >=0.2.6,<3.0.0

test:
  imports:
    - slotscheck
  commands:
    - pip check
    - slotscheck --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ariebovenberg/slotscheck
  doc_url: https://slotscheck.readthedocs.io/en/latest/
  summary: Validate your __slots__
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
