{% set name = "slotscheck" %}
{% set version = "0.16.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/slotscheck-{{ version }}.tar.gz
  sha256: 3ceed3cb325dccffe93a24ffb472c3193b75bc3f5cf613dcacbdb3114ba1f941

build:
  noarch: python
  number: 0
  entry_points:
    - slotscheck = slotscheck.cli:root
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - poetry-core >=1.0.0
    - pip
    - python >=3.6.2,<4
  run:
    - click >=8.0
    - dataclasses >=0.6
    - importlib-metadata >=1,<5
    - python >=3.6.2,<4
    - tomli >=0.2.6,<3.0.0

test:
  imports:
    - slotscheck
  commands:
    - pip check
    - slotscheck --help
  requires:
    - pip

about:
  home: https://github.com/ariebovenberg/slotscheck
  doc_url: https://slotscheck.readthedocs.io/en/latest/
  summary: Validate your __slots__
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
